# Importing the Libraries

In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading the datasets

In [102]:
X_train=pd.read_csv("C:\\Users\\THIS PC\Desktop\Project - 2\Project - 2\Training\X_train.csv")
y_train=pd.read_csv("C:\\Users\\THIS PC\Desktop\Project - 2\Project - 2\Training\y_train.csv")
dataset=pd.merge(X_train,y_train,on="Unique_ID")

In [103]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33050 entries, 0 to 33049
Data columns (total 45 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unique_ID           33050 non-null  object 
 1   C1                  33050 non-null  int64  
 2   C2                  33050 non-null  int64  
 3   C3                  33050 non-null  int64  
 4   C4                  33050 non-null  int64  
 5   C5                  33050 non-null  int64  
 6   C6                  33050 non-null  bool   
 7   C7                  33050 non-null  int64  
 8   C8                  33050 non-null  bool   
 9   N1                  33050 non-null  float64
 10  N2                  28438 non-null  float64
 11  N3                  32685 non-null  float64
 12  N4                  28444 non-null  float64
 13  N5                  28444 non-null  float64
 14  N6                  32685 non-null  float64
 15  N7                  32623 non-null  float64
 16  N8  

In [104]:
dataset.head()

Unique_ID  C1  C2  C3  C4  C5     C6  C7    C8     N1  ...  N27  N28  \
0   Candidate_5926   1   0  11  31   0  False   0  True  23.75  ...  NaN  NaN   
1  Candidate_48134   1   4   2  66   2  False   1  True  11.05  ...  NaN  NaN   
2  Candidate_51717   1   0  19   2   0  False   0  True  29.00  ...  NaN  NaN   
3  Candidate_26401   1   1  16  47   1  False   4  True  17.99  ...  NaN  NaN   
4  Candidate_34872   1   1  13   1   1   True   6  True  27.50  ...  NaN  NaN   

   N29  N30  N31  N32    N33     N34   N35  Dependent_Variable  
0  NaN  NaN  NaN  NaN   58.0  113.39  12.0                   1  
1  NaN  NaN  NaN  NaN  160.0  262.10  17.0                   0  
2  NaN  NaN  NaN  NaN   24.0   50.29  18.0                   1  
3  NaN  NaN  NaN  NaN   70.0  126.52  27.0                   0  
4  NaN  NaN  NaN  NaN  100.0  205.47  21.0                   0  

[5 rows x 45 columns]

In [105]:
dataset.shape

(33050, 45)

In [106]:
dataset.describe()

C1            C2            C3            C4            C5  \
count  33050.000000  33050.000000  33050.000000  33050.000000  33050.000000   
mean       1.119818      2.403873     12.856097     14.437398      1.719395   
std        0.399382      3.399024     12.013457     15.527474      1.320860   
min        1.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      2.000000      1.000000      1.000000   
50%        1.000000      1.000000     10.000000     10.000000      2.000000   
75%        1.000000      3.000000     20.000000     26.000000      2.000000   
max        3.000000     20.000000     51.000000     67.000000      7.000000   

                 C7           N1            N2            N3            N4  \
count  33050.000000  33050.00000  28438.000000  32685.000000  28444.000000   
mean       3.124932     19.97653     81.342710      3.359361      9.574075   
std        2.158905      8.11087     85.397795      0.411040      5.584756   
min        0.000000      0.00000      0.000000      0.000000      0.000000   
25%        1.000000     13.45000     21.000000      3.200000      6.000000   
50%        4.000000     19.27500     53.000000      3.400000      9.000000   
75%        4.000000     26.90000    112.000000      3.600000     13.000000   
max        7.000000     48.00000    755.000000      4.400000     59.000000   

       ...          N27          N28          N29           N30           N31  \
count  ...  6271.000000  6271.000000  6271.000000   6271.000000   6271.000000   
mean   ...    19.512199     0.526391     0.045288   7192.813526   2379.621620   
std    ...    15.637882     2.144069     0.443838   6460.139952   3379.065104   
min    ...     0.000000     0.000000     0.000000   1000.000000      0.000000   
25%    ...     9.000000     0.000000     0.000000   3000.000000      0.000000   
50%    ...    14.000000     0.000000     0.000000   5000.000000   1108.440000   
75%    ...    27.000000     0.000000     0.000000   9500.000000   3408.750000   
max    ...   111.000000    42.000000    11.000000  60001.000000  22586.670000   

               N32           N33           N34           N35  \
count  6220.000000  33050.000000  33050.000000  32623.000000   
mean      0.744373    125.629394    224.313536     19.587254   
std      50.764684    104.391919    186.513844      7.352667   
min    -194.000000     20.000000      0.000000      2.000000   
25%     -31.000000     54.000000     98.740000     14.000000   
50%       0.000000     90.000000    172.600000     19.000000   
75%      32.000000    160.000000    300.947500     24.000000   
max     257.000000    700.000000   2153.380000     64.000000   

       Dependent_Variable  
count        33050.000000  
mean             0.308805  
std              0.462007  
min              0.000000  
25%              0.000000  
50%              0.000000  
75%              1.000000  
max              1.000000  

[8 rows x 42 columns]

In [107]:
dataset.isnull().sum()

Unique_ID                 0
C1                        0
C2                        0
C3                        0
C4                        0
C5                        0
C6                        0
C7                        0
C8                        0
N1                        0
N2                     4612
N3                      365
N4                     4606
N5                     4606
N6                      365
N7                      427
N8                        0
N9                        0
N10                     427
N10.1                   427
N11                     716
N12                    4614
N14                     608
N15                     427
N16                    4606
N17                    4606
N18                    4606
N19                    4571
N20                    4571
N21                    4571
N22                    4571
N23                    2486
N24                       0
N25                   26779
N26                   26779
N27                 

# Deleting the columns having more than 70-75% of missing values.

In [108]:
dataset.drop(dataset.iloc[:,33:41],axis=1,inplace=True)
dataset.shape

(33050, 37)

# Encoding Categorical data

In [109]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
dataset.loc[:,"C6"]=lab.fit_transform(dataset.loc[:,"C6"])
dataset.loc[:,"C8"]=lab.fit_transform(dataset.loc[:,"C8"])
dataset.loc[:,"Unique_ID"]=lab.fit_transform(dataset.loc[:,"Unique_ID"])

In [110]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33050 entries, 0 to 33049
Data columns (total 37 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unique_ID           33050 non-null  int32  
 1   C1                  33050 non-null  int64  
 2   C2                  33050 non-null  int64  
 3   C3                  33050 non-null  int64  
 4   C4                  33050 non-null  int64  
 5   C5                  33050 non-null  int64  
 6   C6                  33050 non-null  int64  
 7   C7                  33050 non-null  int64  
 8   C8                  33050 non-null  int64  
 9   N1                  33050 non-null  float64
 10  N2                  28438 non-null  float64
 11  N3                  32685 non-null  float64
 12  N4                  28444 non-null  float64
 13  N5                  28444 non-null  float64
 14  N6                  32685 non-null  float64
 15  N7                  32623 non-null  float64
 16  N8  

# Dummy Variable Encoding

In [111]:
dataset=pd.get_dummies(dataset)
dataset.head()

Unique_ID  C1  C2  C3  C4  C5  C6  C7  C8     N1  ...      N19   N20   N21  \
0      30342   1   0  11  31   0   0   0   1  23.75  ...      NaN   NaN   NaN   
1      25444   1   4   2  66   2   0   1   1  11.05  ...  25856.0  17.0  0.88   
2      27785   1   0  19   2   0   0   0   1  29.00  ...      NaN   NaN   NaN   
3      10974   1   1  16  47   1   0   4   1  17.99  ...   1006.0   6.0  1.00   
4      16643   1   1  13   1   1   1   6   1  27.50  ...   3398.0  31.0  0.96   

   N22     N23           N24    N33     N34   N35  Dependent_Variable  
0  NaN  27.816   1750.000000   58.0  113.39  12.0                   1  
1  1.0  40.000  10833.333330  160.0  262.10  17.0                   0  
2  NaN  20.000   6250.000000   24.0   50.29  18.0                   1  
3  0.0  26.000   2413.666667   70.0  126.52  27.0                   0  
4  0.0  44.000   7666.666667  100.0  205.47  21.0                   0  

[5 rows x 37 columns]

# Handle Missing values

In [112]:
from sklearn.impute import SimpleImputer
sim=SimpleImputer(missing_values=np.nan,strategy="median")
dataset.iloc[:,10:16]=sim.fit_transform(dataset.iloc[:,10:16])
dataset.iloc[:,18:32]=sim.fit_transform(dataset.iloc[:,18:32])
dataset.loc[:,["N35"]]=sim.fit_transform(dataset.loc[:,["N35"]])

In [113]:
dataset.isnull().sum()

Unique_ID             0
C1                    0
C2                    0
C3                    0
C4                    0
C5                    0
C6                    0
C7                    0
C8                    0
N1                    0
N2                    0
N3                    0
N4                    0
N5                    0
N6                    0
N7                    0
N8                    0
N9                    0
N10                   0
N10.1                 0
N11                   0
N12                   0
N14                   0
N15                   0
N16                   0
N17                   0
N18                   0
N19                   0
N20                   0
N21                   0
N22                   0
N23                   0
N24                   0
N33                   0
N34                   0
N35                   0
Dependent_Variable    0
dtype: int64

In [114]:
X_train.describe()

C1            C2            C3            C4            C5  \
count  33050.000000  33050.000000  33050.000000  33050.000000  33050.000000   
mean       1.119818      2.403873     12.856097     14.437398      1.719395   
std        0.399382      3.399024     12.013457     15.527474      1.320860   
min        1.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      2.000000      1.000000      1.000000   
50%        1.000000      1.000000     10.000000     10.000000      2.000000   
75%        1.000000      3.000000     20.000000     26.000000      2.000000   
max        3.000000     20.000000     51.000000     67.000000      7.000000   

                 C7           N1            N2            N3            N4  \
count  33050.000000  33050.00000  28438.000000  32685.000000  28444.000000   
mean       3.124932     19.97653     81.342710      3.359361      9.574075   
std        2.158905      8.11087     85.397795      0.411040      5.584756   
min        0.000000      0.00000      0.000000      0.000000      0.000000   
25%        1.000000     13.45000     21.000000      3.200000      6.000000   
50%        4.000000     19.27500     53.000000      3.400000      9.000000   
75%        4.000000     26.90000    112.000000      3.600000     13.000000   
max        7.000000     48.00000    755.000000      4.400000     59.000000   

       ...          N26          N27          N28          N29           N30  \
count  ...  6271.000000  6271.000000  6271.000000  6271.000000   6271.000000   
mean   ...    20.084197    19.512199     0.526391     0.045288   7192.813526   
std    ...    16.045120    15.637882     2.144069     0.443838   6460.139952   
min    ...     0.000000     0.000000     0.000000     0.000000   1000.000000   
25%    ...     9.000000     9.000000     0.000000     0.000000   3000.000000   
50%    ...    15.000000    14.000000     0.000000     0.000000   5000.000000   
75%    ...    28.000000    27.000000     0.000000     0.000000   9500.000000   
max    ...   120.000000   111.000000    42.000000    11.000000  60001.000000   

                N31          N32           N33           N34           N35  
count   6271.000000  6220.000000  33050.000000  33050.000000  32623.000000  
mean    2379.621620     0.744373    125.629394    224.313536     19.587254  
std     3379.065104    50.764684    104.391919    186.513844      7.352667  
min        0.000000  -194.000000     20.000000      0.000000      2.000000  
25%        0.000000   -31.000000     54.000000     98.740000     14.000000  
50%     1108.440000     0.000000     90.000000    172.600000     19.000000  
75%     3408.750000    32.000000    160.000000    300.947500     24.000000  
max    22586.670000   257.000000    700.000000   2153.380000     64.000000  

[8 rows x 41 columns]

# Spliting tha dataset into independent and dependent variables

In [115]:
X=dataset.loc[:,dataset.columns!="Dependent_Variable"].values
X

array([[3.0342e+04, 1.0000e+00, 0.0000e+00, ..., 5.8000e+01, 1.1339e+02,
        1.2000e+01],
       [2.5444e+04, 1.0000e+00, 4.0000e+00, ..., 1.6000e+02, 2.6210e+02,
        1.7000e+01],
       [2.7785e+04, 1.0000e+00, 0.0000e+00, ..., 2.4000e+01, 5.0290e+01,
        1.8000e+01],
       ...,
       [1.7394e+04, 1.0000e+00, 1.0000e+00, ..., 4.0000e+01, 6.3590e+01,
        2.0000e+01],
       [1.4509e+04, 1.0000e+00, 0.0000e+00, ..., 2.4000e+01, 4.1600e+01,
        1.7000e+01],
       [2.4765e+04, 1.0000e+00, 6.0000e+00, ..., 1.0000e+02, 2.0410e+02,
        1.1000e+01]])

In [116]:
y=dataset.loc[:,"Dependent_Variable"].values
y

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

# Feature Scaling

In [117]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [118]:
X

array([[ 1.44826699, -0.30001403, -0.70723519, ..., -0.64785107,
        -0.59472912, -1.03757084],
       [ 0.93488818, -0.30001403,  0.46959106, ...,  0.32925083,
         0.20259641, -0.3531273 ],
       [ 1.18025768, -0.30001403, -0.70723519, ..., -0.97355171,
        -0.93304693, -0.2162386 ],
       ...,
       [ 0.09113574, -0.30001403, -0.41302863, ..., -0.82028082,
        -0.86173747,  0.05753882],
       [-0.21125255, -0.30001403, -0.70723519, ..., -0.97355171,
        -0.97963935, -0.3531273 ],
       [ 0.8637195 , -0.30001403,  1.05800418, ..., -0.24551499,
        -0.10837717, -1.17445954]])

# Principal Component Analysis

In [124]:
from sklearn.decomposition import PCA
pca=PCA(n_components=0.95) # 95% of variance
x1=pca.fit_transform(X)
x1,x1.shape


(array([[-2.59916194,  2.5956231 , -3.07196708, ...,  0.1797224 ,
          0.26260436,  0.47948002],
        [ 0.67046294, -1.15049516, -1.24056753, ..., -0.49544534,
          0.05433916, -0.40435015],
        [-2.77814331,  3.66246385, -1.0895353 , ...,  0.79495109,
         -0.2837691 , -0.2549792 ],
        ...,
        [ 1.39915735, -0.85603898,  0.53253558, ..., -0.66659045,
          0.30416144, -0.61696256],
        [-1.93798897,  3.2883363 , -0.63301004, ..., -1.32103332,
         -0.82100868,  0.59936667],
        [-2.96011219, -2.4828484 , -0.70455427, ...,  0.08479838,
         -0.25290274, -0.06904274]]),
 (33050, 27))

# Spliting the dataset into Training set and Testing set 

In [125]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x1,y,test_size=0.3,random_state=42)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(23135, 27) (9915, 27) (23135,) (9915,)


# Build Classification Model


In [179]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

## Logistic regression

In [195]:
log=LogisticRegression()
log.fit(X_train,y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Naive Bayes

In [178]:
nb=GaussianNB()
nb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## KNN

In [183]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

# Confusion Matrix

In [172]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_test_pred)
cm

array([[6342,  548],
       [1380, 1645]], dtype=int64)

# Calculating precision score, recall score, f1 score

In [173]:
from sklearn.metrics import precision_score,recall_score,f1_score
precision_score(y_test,y_test_pred,average="micro")
recall_score(y_test,y_test_pred,average="micro")
f1_score(y_test,y_test_pred,average="micro")

0.805547150781644

# Prediction Probablities

In [186]:
from sklearn.metrics import roc_auc_score,auc
lg_proba=[x[1] for x in log.predict_proba(X_test)]
lg_proba

[0.04927445199092556,
 0.10999982245603088,
 0.24450688410947705,
 0.8305126367884921,
 0.7337076912845876,
 0.7612286641565909,
 0.2674398031336837,
 0.33829676195889136,
 0.08985716660557273,
 0.4720239834932825,
 0.6566541963470284,
 0.03042970677080988,
 0.11117112261813476,
 0.4258053454560404,
 0.2009751965823091,
 0.646825961877581,
 0.03366578201188684,
 0.1218427858984044,
 0.1982069781438665,
 0.7274600790223029,
 0.7405599417958183,
 0.49113945166686274,
 0.33295975482990053,
 0.017004439250810185,
 0.41100824031507416,
 0.46258317977020863,
 0.3436405780529698,
 0.6935657153474724,
 0.5646310912415259,
 0.15393583718252696,
 0.12399738002280407,
 0.18448797660998476,
 0.021208344539823655,
 0.3796905120529438,
 0.40909035612513694,
 0.08791436586707253,
 0.328560514933423,
 0.14321180780099005,
 0.0753813139000758,
 0.07158905940741021,
 0.046058091468878175,
 0.0963382982830476,
 0.44865622988864967,
 0.2982198928333525,
 0.14686258680735007,
 0.8417157868934139,
 0.396238

In [187]:
from sklearn.metrics import roc_auc_score,auc
nb_proba=[x[1] for x in nb.predict_proba(X_test)]
nb_proba

[0.01139013753120394,
 0.042765925802461954,
 0.03730643219606068,
 0.862039356061172,
 0.6212545625970627,
 0.5323915338697381,
 0.037625548330944246,
 0.09110990780756886,
 0.1974063252710941,
 0.08140603694649773,
 0.41299354485441436,
 0.02332305626920399,
 0.04207525965835723,
 0.1152754432656973,
 0.016068249131986415,
 0.49576025792548517,
 0.022736903958020797,
 0.0216329304535997,
 0.0598966703133278,
 0.7484799579462945,
 0.6740430666118715,
 0.14206331873796596,
 0.05243617162374274,
 0.007189673449109446,
 0.9665321677557345,
 0.21557640505727685,
 0.06664744246178064,
 0.9999999996559268,
 0.3573458435424462,
 0.11825355141016923,
 0.02869962472625969,
 0.041951317623754945,
 0.01676252990187777,
 0.1282158926656927,
 0.4841776925445288,
 0.01603602550354524,
 0.4386262099805653,
 0.9885802894318753,
 0.042756316860193724,
 0.03602200047183079,
 0.18827318168894197,
 0.018129793035032843,
 0.08735616405271743,
 0.031090002693195895,
 0.021248231760096298,
 0.97700578418385

In [188]:
from sklearn.metrics import roc_auc_score,auc
knn_proba=[x[1] for x in knn.predict_proba(X_test)]
knn_proba

[0.0,
 0.0,
 0.0,
 0.6,
 0.4,
 0.4,
 0.0,
 0.2,
 0.0,
 0.4,
 0.8,
 0.0,
 0.0,
 0.4,
 0.0,
 0.8,
 0.0,
 0.0,
 0.2,
 0.6,
 0.6,
 0.0,
 0.2,
 0.0,
 0.8,
 0.4,
 0.0,
 0.2,
 0.6,
 0.0,
 0.2,
 0.2,
 0.0,
 0.2,
 0.2,
 0.0,
 0.0,
 0.2,
 0.6,
 0.2,
 0.4,
 0.0,
 0.6,
 0.0,
 0.0,
 0.4,
 0.2,
 0.4,
 0.4,
 0.0,
 0.0,
 0.2,
 0.2,
 0.0,
 0.0,
 0.0,
 0.2,
 0.0,
 0.4,
 0.2,
 0.0,
 0.2,
 0.2,
 0.0,
 0.0,
 0.2,
 0.0,
 0.2,
 0.2,
 0.0,
 0.0,
 0.6,
 0.2,
 0.2,
 0.4,
 0.2,
 0.4,
 0.4,
 0.0,
 0.0,
 0.0,
 0.2,
 0.4,
 0.8,
 0.0,
 0.2,
 0.6,
 0.2,
 0.8,
 0.0,
 0.2,
 0.2,
 0.0,
 0.0,
 0.0,
 0.0,
 0.4,
 0.8,
 0.4,
 0.0,
 0.2,
 0.4,
 0.2,
 0.0,
 0.8,
 0.0,
 0.2,
 0.2,
 0.0,
 0.2,
 0.0,
 0.2,
 0.0,
 0.4,
 0.2,
 0.4,
 0.2,
 0.0,
 0.0,
 0.6,
 0.0,
 0.6,
 0.0,
 0.0,
 0.4,
 0.0,
 0.6,
 0.4,
 0.0,
 0.0,
 0.0,
 0.4,
 0.0,
 0.0,
 0.0,
 0.4,
 0.0,
 0.6,
 0.2,
 0.2,
 0.0,
 0.4,
 0.6,
 0.0,
 0.2,
 1.0,
 0.4,
 0.2,
 0.0,
 0.6,
 0.6,
 0.0,
 0.2,
 0.8,
 0.4,
 0.8,
 0.0,
 0.0,
 0.0,
 0.4,
 0.4,
 0.6,
 0.2,
 0.2,
 0.0,
 0.0,
 0.2

# Computing AUROC and ROC curve Values

In [185]:
from sklearn.metrics import roc_curve, roc_auc_score

In [189]:
lg_auc=roc_auc_score(y_test,lg_proba)
nb_auc=roc_auc_score(y_test,nb_proba)
knn_auc=roc_auc_score(y_test,knn_proba)


# Print AUROC Scores

In [191]:
print("Logistic Regression AUROC = %.3f" %(lg_auc))
print("Naive Bayes AUROC = %.3f" %(nb_auc))
print("KNN AUROC = %.3f" %(knn_auc))

Logistic Regression AUROC = 0.799
Naive Bayes AUROC = 0.758
KNN AUROC = 0.782


In [201]:
y_test_pred=log.predict(X_test)
y_test_pred=pd.DataFrame(y_test_pred)
y_test_pred

0
0     0
1     0
2     0
3     1
4     1
...  ..
9910  0
9911  1
9912  1
9913  0
9914  0

[9915 rows x 1 columns]

In [202]:
y_test_pred.to_csv('submission.csv', index=False)